vh_tokens = (
    'ARROW',
    
    'BASEDLIT',
    'BITSTRLIT',
    'BOX',

    'CHARLIT',
    'COMMENT',

    'DECLIT',

    'EXP',

    'GE',

    'IDENT',

    'LE',

    'MINUS',

    'NE',
    'NEWLINE',

    'SEMI',
    'STRLIT',

    'TICK',

    'VASSIGN'
)

vh2000_reserved = {
    'abs'          : 'ABS',
    'access'       : 'ACCESS',
    'after'        : 'AFTER',
    'alias'        : 'ALIAS',
    'all'          : 'ALL',
    'and'          : 'AND',
    'architecture' : 'ARCHITECTURE',
    'array'        : 'ARRAY',
    'assert'       : 'ASSERT',
    'attribute'    : 'ATTRIBUTE',
    'begin'        : 'BEGIN',
    'block'        : 'BLOCK',
    'body'         : 'BODY',
    'buffer'       : 'BUFFER',
    'bus'          : 'BUS',
    'case'         : 'CASE',
    'component'    : 'COMPONENT',
    'configuration': 'CONFIGURATION',
    'constant'     : 'CONSTANT',
    'disconnect'   : 'DISCONNECT',
    'downto'       : 'DOWNTO',
    'else'         : 'ELSE',
    'elsif'        : 'ELSIF',
    'end'          : 'END',
    'entity'       : 'ENTITY',
    'exit'         : 'EXIT',
    'file'         : 'FILE',
    'for'          : 'FOR',
    'function'     : 'FUNCTION',
    'generate'     : 'GENERATE',
    'generic'      : 'GENERIC',
    'group'        : 'GROUP',
    'guarded'      : 'GUARDED',
    'if'           : 'IF',
    'impure'       : 'IMPURE',
    'in'           : 'IN',
    'inertial'     : 'INERTIAL',
    'inout'        : 'INOUT',
    'is'           : 'IS',
    'label'        : 'LABEL',
    'library'      : 'LIBRARY',
    'linkage'      : 'LINKAGE',
    'literal'      : 'LITERAL',
    'loop'         : 'LOOP',
    'map'          : 'MAP',
    'mod'          : 'MOD',
    'nand'         : 'NAND',
    'new'          : 'NEW',
    'next'         : 'NEXT',
    'nor'          : 'NOR',
    'not'          : 'NOT',
    'null'         : 'NULL',
    'of'           : 'OF',
    'on'           : 'ON',
    'open'         : 'OPEN',
    'or'           : 'OR',
    'others'       : 'OTHERS',
    'out'          : 'OUT',
    'package'      : 'PACKAGE',
    'port'         : 'PORT',
    'postponed'    : 'POSTPONED',
    'procedural'   : 'PROCEDURAL',
    'procedure'    : 'PROCEDURE',
    'process'      : 'PROCESS',
    'protected'    : 'PROTECTED',
    'pure'         : 'PURE',
    'range'        : 'RANGE',
    'record'       : 'RECORD',
    'reference'    : 'REFERENCE',
    'register'     : 'REGISTER',
    'reject'       : 'REJECT',
    'rem'          : 'REM',
    'report'       : 'REPORT',
    'return'       : 'RETURN',
    'rol'          : 'ROL',
    'ror'          : 'ROR',
    'select'       : 'SELECT',
    'severity'     : 'SEVERITY',
    'signal'       : 'SIGNAL',
    'shared'       : 'SHARED',
    'sla'          : 'SLA',
    'sll'          : 'SLL',
    'sra'          : 'SRA',
    'srl'          : 'SRL',
    'subtype'      : 'SUBTYPE',
    'then'         : 'THEN',
    'to'           : 'TO',
    'transport'    : 'TRANSPORT',
    'type'         : 'TYPE',
    'unaffected'   : 'UNAFFECTED',
    'units'        : 'UNITS',
    'until'        : 'UNTIL',
    'use'          : 'USE',
    'variable'     : 'VARIABLE',
    'wait'         : 'WAIT',
    'when'         : 'WHEN',
    'while'        : 'WHILE',
    'with'         : 'WITH',
    'xnor'         : 'XNOR',
    'xor'          : 'XOR'
}